### ISSUE TITLE
[TSDoc Home page]: Horizontal scroll bar appears in 'Code' part when text spacing is enabled.[Sev3][WCAG1.4.12][WCAG2.1]

### ISSUE THREAD

**Issue by SrujanaAnaganti** [microsoft/tsdoc.org-website#21]
**Test Environment:**
OS Build: Windows 10
Browser: Edge Dev
URL: https://tsdoc.org/

**Repro Steps:**
1) Open the above URL and login with valid credentials.
2) TSDoc page will get displayed.
3) Now enable the ‘Text Spacing’.
4) Now navigate to 'Intro' link and activate it.
5) Navigate to 'Code' part which is available in 'What is TSDoc' page and observe the issue.

**Actual:**
Horizontal scroll bar appears in 'Code' part when text spacing is enabled in 'What is TSDoc' page.

**Expected:**
Horizontal scroll bar should not appear in code part when text spacing is enabled in 'What is TSDoc' page.

**User Experience:**
Users with dyslexia and low vision who need to increase space between text to make a better experience will be impacted if horizontal scroll bar appears in 'Code' part when applying Text spacing.

**Note:** This issue is repro through out the TSDoc URL where ever 'Code' part is available.

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/text-spacing
<img width="960" alt="Horizontal scroll bar appears in 'Code' part when text spacing is enabled" src="https://user-images.githubusercontent.com/85154417/121008586-c64c6900-c7b0-11eb-9ffb-0b24f099100e.png">

**Comment by octogonz** [comment]
This issue has been closed because this Jekyll project has been retired. The documentation content has been migrated to Docusaurus. 

If the problem has not been addressed, please file a new issue under this GitHub project instead:  

https://github.com/microsoft/rushstack-websites
