### ISSUE TITLE
Accessibility Release test pass for TSDoc on Web - April23 (A11ytest_tracking, Feature_Task , TSDoc)

### ISSUE THREAD

**Issue by Raisul123** [microsoft/tsdoc.org-website#59]

**Comment by octogonz** [comment]
This issue has been closed because this Jekyll project has been retired. The documentation content has been migrated to Docusaurus. 

If the problem has not been addressed, please file a new issue under this GitHub project instead:  

https://github.com/microsoft/rushstack-websites
